name: deploy-expiration

on:
  push:
    branches:
      - master
    paths:
      - 'expiration/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd expiration && docker build -t josephlum/expiration .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push josephlum/expiration
      - uses: digitalocean/action-doctl@v2  # Installing doctl (by DigitalOcean) into container
        with:
          token: $ {{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment expiration-depl   # Restart deployment to use the latest docker image
