name: deploy-orders

on:
  push:
    branches:
      - master
    paths:
      - 'orders/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && docker build -t josephlum/orders .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push josephlum/orders
      - uses: digitalocean/action-doctl@v2  # Installing doctl (by DigitalOcean) into container
        with:
          token: $ {{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment orders-depl   # Restart deployment to use the latest docker image
