name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**' # Only run jobs when files in path change
  
jobs:
  build:  # To startup and run a container in a VM
    runs-on: ubuntu-latest  # Runs on the latest version of ubuntu
    steps:
      - uses: actions/checkout@v2   # Take all the code out of our project
      - run: cd orders && npm install && npm run test:ci  # Run commands
